sudo: required
addons:
  apt:
    packages:
    - bsdtar
    - dosfstools
script:
- sudo ./build.sh ArchLinuxARM-rpi-latest
- sudo ./build.sh ArchLinuxARM-rpi-2-latest
- sudo ./build.sh ArchLinuxARM-rpi-3-latest
- sudo ./build.sh ArchLinuxARM-rpi-4-latest
- sudo ./build.sh ArchLinuxARM-rpi-aarch64-latest
deploy:
  provider: releases
  api_key: '$GITHUB_TOKEN'
  file:
  - ArchLinuxARM-rpi-latest.img.zip
  - ArchLinuxARM-rpi-2-latest.img.zip
  - ArchLinuxARM-rpi-3-latest.img.zip
  - ArchLinuxARM-rpi-4-latest.img.zip
  - ArchLinuxARM-rpi-aarch64-latest.img.zip
  skip_cleanup: true
  on:
    tags: true
